name: Arduino-watering-system

services:
  app:
    build:
      dockerfile: Dockerfile
      pull: true
    command: ./build/bin/Arduino-watering-system
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
