name: Arduino-watering-system

services:
  desktop-env:
    container_name: desktop-env
    build:
      target: desktop-env
      dockerfile: Dockerfile
      pull: true
    environment:
      - DISPLAY=$DISPLAY
      - TYPE=CLAYDESKTOP
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/app
    command: sleep infinity
  hardware-env:
    container_name: hardware-env
    build:
      target: hardware-env
      dockerfile: Dockerfile
      pull: true
    volumes:
      - .:/app
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    command: sleep infinity
